spring:
  redis:
    cluster:
      # 各 Redis 节点信息
      nodes: 122.152.197.167:6379,122.152.197.167:6380,122.152.197.167:6381,122.152.197.167:6382,122.152.197.167:6383,122.152.197.167:6384
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
    password: 123456
#    main:
#      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册（springboot 2.1.x 并不支持这种操作）

server:
  port: 8089
